### PR TITLE
Riddim and param

### PR DESCRIPTION
**Pull request by ryanlaws**

### CODE REVIEW

**Comment by tyleretters** [comment]
@ryanlaws sorry, @Quixotic7 got in line with #7 first

**Review by tyleretters — CHANGES_REQUESTED** [review]
resolve merge conflicts plz

**Comment by tyleretters** [comment]
testing webhook

**Comment by tyleretters** [comment]
testing comment with github webook to discord

**Comment by ryanlaws** [comment]
> resolve merge conflicts plz

Done!

**Pull request merged**
